version: '3.4'

services:

  scout:
    build: .
    hostname: scout
    environment:
      TERM: xterm-color
      APACHE_RUN_USER: buildkit
    links:
      - mysql
    ports:
      - "8090:80"
    volumes:
      - /var/www:/var/www
      - /home/michael/.git:/buildkit/.git
      - .:/scout
      - scout:/buildkit/.scout
      - ./.bash_history:/buildkit/.bash_history
      - /home/michael/.ssh:/buildkit/.ssh

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: buildkit
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8091:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: buildkit
    restart: always

  maildev:
    image: djfarrelly/maildev
    ports:
      - "8092:80"
    restart: always

volumes:
  mysql:
  scout:
